server:

  port: ${PORT:${SERVERS_PORT:0}}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-user
    username: root
    password: Sasha24!


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    non-secure-port: ${server.port} # Esto le dice a Eureka qué puerto usar para el registro
    prefer-ip-address: true # Sigue siendo una buena práctica
jwt:
  secret: secret